-- USERS TABLE (UPDATED)
CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  unlock_until INTEGER NOT NULL,
  role TEXT DEFAULT 'member',        -- NEW
  created_at INTEGER DEFAULT (strftime('%s','now'))  -- NEW
);

-- LOGIN LOGS
CREATE TABLE IF NOT EXISTS login_logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  timestamp INTEGER NOT NULL,
  ip TEXT
);

-- MESSAGES (Guild Message Center)
CREATE TABLE IF NOT EXISTS messages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  message TEXT NOT NULL,
  timestamp INTEGER NOT NULL
);

-- NOTIFICATIONS (System → User)
CREATE TABLE IF NOT EXISTS notifications (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  timestamp INTEGER NOT NULL,
  read INTEGER DEFAULT 0
);

-- PAYMENTS (Entry + Renewals)
CREATE TABLE IF NOT EXISTS payments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  amount REAL NOT NULL,
  timestamp INTEGER NOT NULL,
  method TEXT
);
